In [1]:
import pandas as pd

In [2]:
file_one = "../db/northamerica_station_information.csv"

In [3]:
file_two = "../db/city_gasday_fcstupdated.csv"

In [4]:
file_one_df = pd.read_csv(file_one)

In [5]:
file_one_df.head()

  identifier     lat      lon              name state country
0       CYEG  53.310 -113.579  Edmonton Interna    AB      CA
1       CYHZ  44.881  -63.509  Halifax Internat    NS      CA
2       CYQB  46.791  -71.393  Quebec/Jean Lesa    QC      CA
3       CYQR  50.432 -104.666  Regina Internati    SK      CA
4       CYUL  45.471  -73.741  Montreal/Trudeau    QC      CA

In [6]:
file_one_df.rename(columns = {"identifier": "Station"}, inplace = True)

In [7]:
file_one_df.head()

  Station     lat      lon              name state country
0    CYEG  53.310 -113.579  Edmonton Interna    AB      CA
1    CYHZ  44.881  -63.509  Halifax Internat    NS      CA
2    CYQB  46.791  -71.393  Quebec/Jean Lesa    QC      CA
3    CYQR  50.432 -104.666  Regina Internati    SK      CA
4    CYUL  45.471  -73.741  Montreal/Trudeau    QC      CA

In [8]:
file_two_df = pd.read_csv(file_two, encoding="ISO-8859-1")

In [9]:
file_two_df.head()

,Production Date,Date,Station,Fcst Mn,Fcst Mx,Fcst Avg,Norm Mn,Norm Max,HDD,CDD
0,12/17/2018,12/17/2018,KABR,18,43,30.5,5.2,24.7,35,0
1,12/17/2018,12/18/2018,KABR,18,41,29.5,4.9,24.5,36,0
2,12/17/2018,12/19/2018,KABR,22,44,33.0,4.6,24.2,32,0
3,12/17/2018,12/20/2018,KABR,16,39,27.5,4.4,24.0,38,0
4,12/17/2018,12/21/2018,KABR,18,37,27.5,4.1,23.8,38,0

In [10]:
merge_table = pd.merge(file_one_df, file_two_df, on="Station", how="right")
merge_table.head()

,Station,lat,lon,name,state,country,Production Date,Date,Fcst Mn,Fcst Mx,Fcst Avg,Norm Mn,Norm Max,HDD,CDD
0,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/17/2018,17,37,27.0,3.0,22.0,38,0
1,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/18/2018,20,35,27.5,2.0,22.0,38,0
2,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/19/2018,12,37,24.5,2.0,22.0,41,0
3,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/20/2018,13,33,23.0,2.0,22.0,42,0
4,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/21/2018,4,28,16.0,2.0,22.0,49,0

In [11]:
del merge_table["HDD"]

In [12]:
del merge_table["CDD"]

In [13]:
merge_table.head()

,Station,lat,lon,name,state,country,Production Date,Date,Fcst Mn,Fcst Mx,Fcst Avg,Norm Mn,Norm Max
0,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/17/2018,17,37,27.0,3.0,22.0
1,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/18/2018,20,35,27.5,2.0,22.0
2,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/19/2018,12,37,24.5,2.0,22.0
3,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/20/2018,13,33,23.0,2.0,22.0
4,CYEG,53.31,-113.579,Edmonton Interna,AB,CA,12/17/2018,12/21/2018,4,28,16.0,2.0,22.0

In [14]:
new_df = merge_table.loc[merge_table["country"] == "US",:]

In [15]:
new_df.head()

,Station,lat,lon,name,state,country,Production Date,Date,Fcst Mn,Fcst Mx,Fcst Avg,Norm Mn,Norm Max
126,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/17/2018,29,43,36.0,23.5,39.8
127,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/18/2018,22,38,30.0,23.2,39.5
128,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/19/2018,25,44,34.5,23.0,39.2
129,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/20/2018,33,58,45.5,22.7,38.9
130,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/21/2018,42,62,52.0,22.5,38.6

In [16]:
new_df1 = new_df.rename(columns = {"Station":"station_id","name":"station_name","Production Date":"production_date","Date":"forecast_date",
                         "Fcst Mn":"fcst_mn","Fcst Mx":"fcst_mx","Fcst Avg":"fcst_avg","Norm Mn":"norm_mn","Norm Max":"norm_mx"
                        })

In [17]:
new_df1.reset_index().rename(columns = {new_df1.index.name: "id"})

,index,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx
0,126,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/17/2018,29,43,36.0,23.5,39.8
1,127,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/18/2018,22,38,30.0,23.2,39.5
2,128,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/19/2018,25,44,34.5,23.0,39.2
3,129,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/20/2018,33,58,45.5,22.7,38.9
4,130,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/21/2018,42,62,52.0,22.5,38.6
5,131,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/22/2018,32,45,38.5,22.2,38.4
6,132,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/23/2018,29,42,35.5,22.0,38.2
7,133,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/24/2018,26,41,33.5,21.8,37.9
8,134,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/25/2018,25,40,32.5,21.6,37.7
9,135,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/26/2018,29,44,36.5,21.4,37.5
10,136,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/27/2018,28,44,36.0,21.2,37.3
11,137,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/28/2018,30,46,38.0,21.0,37.1
12,138,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/29/2018,31,46,38.5,20.8,37.0
13,139,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/30/2018,27,44,35.5,20.6,36.8
14,140,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/17/2018,38,57,47.5,33.1,56.2
15,141,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/18/2018,40,61,50.5,33.0,56.1
16,142,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/19/2018,42,63,52.5,32.9,56.0
17,143,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/20/2018,35,59,47.0,32.8,55.9
18,144,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/21/2018,39,65,52.0,32.7,55.9
19,145,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/22/2018,38,65,51.5,32.7,55.8
20,146,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/23/2018,39,64,51.5,32.6,55.7
21,147,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/24/2018,42,64,53.0,32.6,55.7
22,148,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/25/2018,46,65,55.5,32.5,55.7
23,149,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/26/2018,40,62,51.0,32.5,55.7
24,150,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/27/2018,37,61,49.0,32.5,55.7
25,151,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/28/2018,33,55,44.0,32.5,55.7
26,152,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/29/2018,33,55,44.0,32.5,55.7
27,153,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/30/2018,34,55,44.5,32.5,55.7
28,154,KABQ,35.050,-106.617,ALBUQUERQUE,NM,US,12/17/2018,12/17/2018,35,51,43.0,26.1,45.4
29,155,KABQ,35.050,-106.617,ALBUQUERQUE,NM,US,12/17/2018,12/18/2018,29,51,40.0,26.0,45.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3890,4016,KWMC,40.900,-117.800,WINNEMUCCA,NV,US,12/17/2018,12/29/2018,7,32,19.5,16.9,40.2
3891,4017,KWMC,40.900,-117.800,WINNEMUCCA,NV,US,12/17/2018,12/30/2018,6,31,18.5,17.0,40.3
3892,4018,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/17/2018,31,48,39.5,20.7,34.7
3893,4019,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/18/2018,34,51,42.5,20.7,34.6
3894,4020,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/19/2018,32,50,41.0,20.6,34.5
3895,4021,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/20/2018,28,47,37.5,20.6,34.4
3896,4022,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/21/2018,24,43,33.5,20.6,34.3
3897,4023,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/22/2018,26,39,32.5,20.6,34.3
3898,4024,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/23/2018,25,39,32.0,20.6,34.3
3899,4025,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/24/2018,21,38,29.5,20.7,34.3
3900,4026,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/25/2018,20,37,28.5,20.7,34.3
3901,4027,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/26/2018,19,34,26.5,20.8,34.3
3902,4028,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/27/2018,17,34,25.5,20.8,34.4
3903,4029,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/28/2018,20,36,28.0,20.9,34.5
3904,4030,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/29/2018,18,35,26.5,21.0,34.6
3905,4031,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/30/2018,19,35,27.0,21.1,34.7
3906,4032,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/17/2018,29,37,33.0,23.4,35.7
3907,4033,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/18/2018,25,38,31.5,23.1,35.5
3908,4034,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/19/2018,28,45,36.5,22.8,35.2
3909,4035,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/20/2018,36,48,42.0,22.5,34.9
3910,4036,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/21/2018,32,45,38.5,22.2,34.7
3911,4037,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/22/2018,29,35,32.0,22.0,34.5
3912,4038,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/23/2018,27,37,32.0,21.7,34.3
3913,4039,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/24/2018,25,36,30.5,21.5,34.1
3914,4040,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/25/2018,25,37,31.0,21.2,33.9
3915,4041,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/26/2018,30,43,36.5,21.0,33.7
3916,4042,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/27/2018,31,45,38.0,20.8,33.5
3917,4043,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/28/2018,31,45,38.0,20.6,33.4
3918,4044,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/29/2018,28,43,35.5,20.4,33.2
3919,4045,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/30/2018,27,41,34.0,20.2,33.1

In [18]:
# new_df1['id'] = range(1, len(new_df1) + 1)

In [19]:
new_df1['id'] = new_df1.index

In [20]:
new_df1.set_index('id')

,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx
id,,,,,,,,,,,,,
126,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/17/2018,29,43,36.0,23.5,39.8
127,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/18/2018,22,38,30.0,23.2,39.5
128,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/19/2018,25,44,34.5,23.0,39.2
129,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/20/2018,33,58,45.5,22.7,38.9
130,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/21/2018,42,62,52.0,22.5,38.6
131,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/22/2018,32,45,38.5,22.2,38.4
132,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/23/2018,29,42,35.5,22.0,38.2
133,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/24/2018,26,41,33.5,21.8,37.9
134,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/25/2018,25,40,32.5,21.6,37.7
135,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/26/2018,29,44,36.5,21.4,37.5
136,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/27/2018,28,44,36.0,21.2,37.3
137,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/28/2018,30,46,38.0,21.0,37.1
138,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/29/2018,31,46,38.5,20.8,37.0
139,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/30/2018,27,44,35.5,20.6,36.8
140,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/17/2018,38,57,47.5,33.1,56.2
141,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/18/2018,40,61,50.5,33.0,56.1
142,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/19/2018,42,63,52.5,32.9,56.0
143,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/20/2018,35,59,47.0,32.8,55.9
144,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/21/2018,39,65,52.0,32.7,55.9
145,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/22/2018,38,65,51.5,32.7,55.8
146,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/23/2018,39,64,51.5,32.6,55.7
147,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/24/2018,42,64,53.0,32.6,55.7
148,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/25/2018,46,65,55.5,32.5,55.7
149,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/26/2018,40,62,51.0,32.5,55.7
150,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/27/2018,37,61,49.0,32.5,55.7
151,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/28/2018,33,55,44.0,32.5,55.7
152,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/29/2018,33,55,44.0,32.5,55.7
153,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/30/2018,34,55,44.5,32.5,55.7
154,KABQ,35.050,-106.617,ALBUQUERQUE,NM,US,12/17/2018,12/17/2018,35,51,43.0,26.1,45.4
155,KABQ,35.050,-106.617,ALBUQUERQUE,NM,US,12/17/2018,12/18/2018,29,51,40.0,26.0,45.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4016,KWMC,40.900,-117.800,WINNEMUCCA,NV,US,12/17/2018,12/29/2018,7,32,19.5,16.9,40.2
4017,KWMC,40.900,-117.800,WINNEMUCCA,NV,US,12/17/2018,12/30/2018,6,31,18.5,17.0,40.3
4018,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/17/2018,31,48,39.5,20.7,34.7
4019,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/18/2018,34,51,42.5,20.7,34.6
4020,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/19/2018,32,50,41.0,20.6,34.5
4021,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/20/2018,28,47,37.5,20.6,34.4
4022,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/21/2018,24,43,33.5,20.6,34.3
4023,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/22/2018,26,39,32.5,20.6,34.3
4024,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/23/2018,25,39,32.0,20.6,34.3
4025,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/24/2018,21,38,29.5,20.7,34.3
4026,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/25/2018,20,37,28.5,20.7,34.3
4027,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/26/2018,19,34,26.5,20.8,34.3
4028,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/27/2018,17,34,25.5,20.8,34.4
4029,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/28/2018,20,36,28.0,20.9,34.5
4030,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/29/2018,18,35,26.5,21.0,34.6
4031,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/30/2018,19,35,27.0,21.1,34.7
4032,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/17/2018,29,37,33.0,23.4,35.7
4033,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/18/2018,25,38,31.5,23.1,35.5
4034,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/19/2018,28,45,36.5,22.8,35.2
4035,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/20/2018,36,48,42.0,22.5,34.9
4036,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/21/2018,32,45,38.5,22.2,34.7
4037,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/22/2018,29,35,32.0,22.0,34.5
4038,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/23/2018,27,37,32.0,21.7,34.3
4039,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/24/2018,25,36,30.5,21.5,34.1
4040,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/25/2018,25,37,31.0,21.2,33.9
4041,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/26/2018,30,43,36.5,21.0,33.7
4042,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/27/2018,31,45,38.0,20.8,33.5
4043,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/28/2018,31,45,38.0,20.6,33.4
4044,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/29/2018,28,43,35.5,20.4,33.2
4045,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/30/2018,27,41,34.0,20.2,33.1

In [21]:
new_df1.loc()

In [22]:
new_df1.head()

,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx,id
126,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/17/2018,29,43,36.0,23.5,39.8,126
127,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/18/2018,22,38,30.0,23.2,39.5,127
128,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/19/2018,25,44,34.5,23.0,39.2,128
129,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/20/2018,33,58,45.5,22.7,38.9,129
130,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/21/2018,42,62,52.0,22.5,38.6,130

In [23]:
new_df1 = new_df1.reset_index()

In [24]:
new_df1.head()

,index,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx,id
0,126,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/17/2018,29,43,36.0,23.5,39.8,126
1,127,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/18/2018,22,38,30.0,23.2,39.5,127
2,128,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/19/2018,25,44,34.5,23.0,39.2,128
3,129,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/20/2018,33,58,45.5,22.7,38.9,129
4,130,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/21/2018,42,62,52.0,22.5,38.6,130

In [25]:
del new_df1["index"]

In [26]:
del new_df1["id"]

In [27]:
new_df1.head()

,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx
0,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/17/2018,29,43,36.0,23.5,39.8
1,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/18/2018,22,38,30.0,23.2,39.5
2,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/19/2018,25,44,34.5,23.0,39.2
3,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/20/2018,33,58,45.5,22.7,38.9
4,KABE,40.65,-75.45,ALLENTOWN,PA,US,12/17/2018,12/21/2018,42,62,52.0,22.5,38.6

In [28]:
day_df = new_df1.loc[new_df1["forecast_date"] == "12/25/2018",:]

In [29]:
day_df

,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx
8,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/25/2018,25,40,32.5,21.6,37.7
22,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/25/2018,46,65,55.5,32.5,55.7
36,KABQ,35.050,-106.617,ALBUQUERQUE,NM,US,12/17/2018,12/25/2018,30,53,41.5,25.6,45.1
50,KABR,45.460,-98.410,ABERDEEN,SD,US,12/17/2018,12/25/2018,15,31,23.0,3.3,23.1
64,KACT,31.617,-97.233,WACO,TX,US,12/17/2018,12/25/2018,49,68,58.5,36.1,57.5
78,KACV,40.983,-124.100,ARCATA/EUREKA,CA,US,12/17/2018,12/25/2018,37,52,44.5,38.3,54.3
92,KACY,39.467,-74.583,ATLANTIC CITY,NJ,US,12/17/2018,12/25/2018,25,43,34.0,26.1,43.6
106,KAGS,33.367,-81.967,AUGUSTA/BUSH,GA,US,12/17/2018,12/25/2018,37,62,49.5,33.2,57.9
120,KAHN,33.950,-83.333,ATHENS,GA,US,12/17/2018,12/25/2018,37,57,47.0,33.6,53.8
134,KAKR,41.033,-81.467,AKRON (FULTON),OH,US,12/17/2018,12/25/2018,27,39,33.0,22.2,34.9
148,KALB,42.750,-73.800,ALBANY,NY,US,12/17/2018,12/25/2018,20,34,27.0,17.9,32.8
162,KALO,42.550,-92.400,WATERLOO,IA,US,12/17/2018,12/25/2018,21,35,28.0,11.0,28.1
176,KALW,46.100,-118.283,WALLA WALLA,WA,US,12/17/2018,12/25/2018,31,40,35.5,27.5,37.6
190,KAMA,35.217,-101.717,AMARILLO,TX,US,12/17/2018,12/25/2018,31,56,43.5,23.2,48.8
204,KANJ,46.467,-84.367,SAULT STE MARIE,MI,US,12/17/2018,12/25/2018,14,28,21.0,12.1,25.9
218,KAPC,38.200,-122.283,NAPA,CA,US,12/17/2018,12/25/2018,35,57,46.0,35.9,54.5
232,KAPN,45.067,-83.567,ALPENA,MI,US,12/17/2018,12/25/2018,19,30,24.5,15.4,29.1
246,KAST,46.150,-123.883,ASTORIA,OR,US,12/17/2018,12/25/2018,36,50,43.0,36.5,48.3
260,KATL,33.633,-84.450,ATLANTA,GA,US,12/17/2018,12/25/2018,40,58,49.0,34.9,52.1
274,KATT,30.317,-97.767,AUSTIN/MABRY,TX,US,12/17/2018,12/25/2018,53,70,61.5,41.2,61.2
288,KAUS,30.183,-97.683,AUSTIN,TX,US,12/17/2018,12/25/2018,54,72,63.0,36.0,62.5
302,KAVL,35.433,-82.533,ASHEVILLE,NC,US,12/17/2018,12/25/2018,34,52,43.0,27.8,47.7
316,KAVP,41.333,-75.717,AVOCA/WILKES B.,PA,US,12/17/2018,12/25/2018,23,35,29.0,21.0,34.8
330,KAZO,42.233,-85.550,KALAMAZOO,MI,US,12/17/2018,12/25/2018,24,36,30.0,20.1,32.3
344,KBAF,42.167,-72.717,WESTFIELD,MA,US,12/17/2018,12/25/2018,19,36,27.5,17.5,35.5
358,KBAZ,29.717,-98.050,NEW BRAUNFELS,TX,US,12/17/2018,12/25/2018,56,72,64.0,39.5,62.3
372,KBDL,41.933,-72.683,WINDSOR LOCKS,CT,US,12/17/2018,12/25/2018,20,36,28.0,20.3,36.7
386,KBDR,41.167,-73.133,BRIDGEPORT,CT,US,12/17/2018,12/25/2018,26,40,33.0,25.5,39.5
400,KBFF,41.867,-103.583,SCOTTSBLUFF,NE,US,12/17/2018,12/25/2018,17,44,30.5,11.8,38.9
414,KBFL,35.433,-119.050,BAKERSFIELD,CA,US,12/17/2018,12/25/2018,42,52,47.0,38.6,55.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3508,KSJC,37.367,-121.917,SAN JOSE,CA,US,12/17/2018,12/25/2018,41,55,48.0,41.7,60.2
3522,KSJT,31.367,-100.500,SAN ANGELO,TX,US,12/17/2018,12/25/2018,45,68,56.5,32.7,58.7
3536,KSLC,40.783,-111.967,SALT LAKE CITY,UT,US,12/17/2018,12/25/2018,27,37,32.0,21.7,36.6
3550,KSLE,44.900,-123.000,SALEM,OR,US,12/17/2018,12/25/2018,34,49,41.5,33.5,45.4
3564,KSNS,36.667,-121.600,SALINAS,CA,US,12/17/2018,12/25/2018,40,55,47.5,40.4,60.5
3578,KSPI,39.850,-89.683,SPRINGFIELD,IL,US,12/17/2018,12/25/2018,28,41,34.5,20.2,35.7
3592,KSPS,33.983,-98.500,WICHITA FALL,TX,US,12/17/2018,12/25/2018,41,62,51.5,29.6,53.2
3606,KSRQ,27.400,-82.567,SARASOTA/BRADENT,FL,US,12/17/2018,12/25/2018,57,75,66.0,52.3,71.7
3620,KSTC,45.550,-94.050,ST. CLOUD,MN,US,12/17/2018,12/25/2018,15,27,21.0,4.2,22.3
3634,KSTL,38.750,-90.367,ST. LOUIS,MO,US,12/17/2018,12/25/2018,33,47,40.0,24.8,40.2
3648,KSTS,38.500,-122.817,SANTA ROSA,CA,US,12/17/2018,12/25/2018,34,57,45.5,36.1,55.5
3662,KSUX,42.383,-96.383,SIOUX CITY,IA,US,12/17/2018,12/25/2018,24,39,31.5,10.9,30.0
3676,KSYR,43.117,-76.100,SYRACUSE,NY,US,12/17/2018,12/25/2018,17,30,23.5,19.2,33.6
3690,KTHV,39.917,-76.883,YORK,PA,US,12/17/2018,12/25/2018,24,39,31.5,22.0,39.9
3704,KTLH,30.400,-84.350,TALLAHASSEE,FL,US,12/17/2018,12/25/2018,45,68,56.5,39.7,63.7
3718,KTOL,41.583,-83.800,TOLEDO,OH,US,12/17/2018,12/25/2018,26,38,32.0,20.6,33.8
3732,KTOP,39.067,-95.633,TOPEKA,KS,US,12/17/2018,12/25/2018,31,48,39.5,20.6,39.7
3746,KTPA,27.967,-82.533,TAMPA,FL,US,12/17/2018,12/25/2018,56,73,64.5,52.5,70.5
3760,KTTN,40.283,-74.817,TRENTON,NJ,US,12/17/2018,12/25/2018,26,40,33.0,24.8,40.6
3774,KTUL,36.200,-95.883,TULSA,OK,US,12/17/2018,12/25/2018,38,56,47.0,28.0,47.5
3788,KTUS,32.133,-110.950,TUCSON,AZ,US,12/17/2018,12/25/2018,40,66,53.0,38.5,63.9
3802,KTYR,32.367,-95.400,TYLER,TX,US,12/17/2018,12/25/2018,50,67,58.5,37.8,56.4
3816,KTYS,35.817,-83.983,KNOXVILLE,TN,US,12/17/2018,12/25/2018,33,52,42.5,30.2,47.7
3830,KUIL,47.933,-124.550,QUILLAYUTE,WA,US,12/17/2018,12/25/2018,33,47,40.0,34.6,45.6
3844,KVCT,28.867,-96.933,VICTORIA,TX,US,12/17/2018,12/25/2018,60,75,67.5,43.2,64.7
3858,KVIS,36.313,-119.388,Visalia Airport,CA,US,12/17/2018,12/25/2018,38,52,45.0,37.3,53.2
3872,KVTN,42.867,-100.550,VALENTINE,NE,US,12/17/2018,12/25/2018,19,43,31.0,9.8,35.7
3886,KWMC,40.900,-117.800,WINNEMUCCA,NV,US,12/17/2018,12/25/2018,15,37,26.0,16.8,40.2
3900,KYKM,46.567,-120.533,YAKIMA,WA,US,12/17/2018,12/25/2018,20,37,28.5,20.7,34.3
3914,KYNG,41.250,-80.667,YOUNGSTOWN,OH,US,12/17/2018,12/25/2018,25,37,31.0,21.2,33.9

In [30]:
day_df["station_id"].nunique()

280

In [31]:
day_df = day_df.reset_index()

In [32]:
day_df.head()

,index,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx
0,8,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/25/2018,25,40,32.5,21.6,37.7
1,22,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/25/2018,46,65,55.5,32.5,55.7
2,36,KABQ,35.050,-106.617,ALBUQUERQUE,NM,US,12/17/2018,12/25/2018,30,53,41.5,25.6,45.1
3,50,KABR,45.460,-98.410,ABERDEEN,SD,US,12/17/2018,12/25/2018,15,31,23.0,3.3,23.1
4,64,KACT,31.617,-97.233,WACO,TX,US,12/17/2018,12/25/2018,49,68,58.5,36.1,57.5

In [33]:
del day_df["index"]

In [34]:
day_df.head()

,station_id,lat,lon,station_name,state,country,production_date,forecast_date,fcst_mn,fcst_mx,fcst_avg,norm_mn,norm_mx
0,KABE,40.650,-75.450,ALLENTOWN,PA,US,12/17/2018,12/25/2018,25,40,32.5,21.6,37.7
1,KABI,32.417,-99.683,ABILENE,TX,US,12/17/2018,12/25/2018,46,65,55.5,32.5,55.7
2,KABQ,35.050,-106.617,ALBUQUERQUE,NM,US,12/17/2018,12/25/2018,30,53,41.5,25.6,45.1
3,KABR,45.460,-98.410,ABERDEEN,SD,US,12/17/2018,12/25/2018,15,31,23.0,3.3,23.1
4,KACT,31.617,-97.233,WACO,TX,US,12/17/2018,12/25/2018,49,68,58.5,36.1,57.5

In [35]:
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float 
from sqlalchemy.ext.automap import automap_base
import pymysql
pymysql.install_as_MySQLdb()

In [36]:
Base = declarative_base()

class Data(Base):
    __tablename__ = 'data'
    id = Column(Integer, primary_key=True)
    station_id = Column(String(255))
    lat = Column(Integer)
    lon = Column(Integer)
    station_name = Column(String(255))
    state = Column(String(255))
    country = Column(String(255))
    production_date = Column(Integer)
    forecast_date = Column(Integer)
    #fcst_mn = Column(Integer)
    #fcst_mx = Column(Integer)
    fcst_avg = Column(Integer)
    norm_mn = Column(Integer)
    norm_mx = Column(Integer)

In [37]:
engine = create_engine("sqlite:///dataupdated.sqlite")
conn = engine.connect()

In [38]:
Base.metadata.create_all(engine)

In [39]:
from sqlalchemy.orm import Session
session = Session(bind=engine)

In [40]:
for i in range(len(day_df)):
    data = Data(station_id=day_df["station_id"][i],
                lat=day_df["lat"][i],
                lon=day_df["lon"][i],
                station_name=day_df["station_name"][i],
                state=day_df["state"][i],
                country=day_df["country"][i],
                production_date=day_df["production_date"][i],
                forecast_date=day_df["forecast_date"][i],
                #fcst_mn=new_df1["fcst_mn"][i],
                #fcst_mx=new_df1["fcst_mx"][i],
                fcst_avg=day_df["fcst_avg"][i],
                norm_mn=day_df["norm_mn"][i],
                norm_mx=day_df["norm_mx"][i])
    session.add(data)
    session.commit()

In [41]:
qaz = engine.execute("SELECT * FROM data")

In [42]:
for record in qaz:
    print(record)

(1, 'KABE', 40.65, -75.45, 'ALLENTOWN       ', 'PA', 'US', '12/17/2018', '12/25/2018', 32.5, 21.6, 37.7)
(2, 'KABI', 32.417, -99.68299999999999, 'ABILENE         ', 'TX', 'US', '12/17/2018', '12/25/2018', 55.5, 32.5, 55.7)
(3, 'KABQ', 35.05, -106.617, 'ALBUQUERQUE     ', 'NM', 'US', '12/17/2018', '12/25/2018', 41.5, 25.6, 45.1)
(4, 'KABR', 45.46, -98.41, 'ABERDEEN', 'SD', 'US', '12/17/2018', '12/25/2018', 23, 3.3, 23.1)
(5, 'KACT', 31.616999999999997, -97.23299999999999, 'WACO            ', 'TX', 'US', '12/17/2018', '12/25/2018', 58.5, 36.1, 57.5)
(6, 'KACV', 40.983000000000004, -124.1, 'ARCATA/EUREKA   ', 'CA', 'US', '12/17/2018', '12/25/2018', 44.5, 38.3, 54.3)
(7, 'KACY', 39.467, -74.583, 'ATLANTIC CITY   ', 'NJ', 'US', '12/17/2018', '12/25/2018', 34, 26.1, 43.6)
(8, 'KAGS', 33.367, -81.96700000000001, 'AUGUSTA/BUSH    ', 'GA', 'US', '12/17/2018', '12/25/2018', 49.5, 33.2, 57.9)
(9, 'KAHN', 33.95, -83.333, 'ATHENS          ', 'GA', 'US', '12/17/2018', '12/25/2018', 47, 33.6, 53.8)
(10, 'KAKR', 41.033, -81.467, 'AKRON (FULTON)  ', 'OH', 'US', '12/17/2018', '12/25/2018', 33, 22.2, 34.9)
(11, 'KALB', 42.75, -73.8, 'ALBANY          ', 'NY', 'US', '12/17/2018', '12/25/2018', 27, 17.9, 32.8)
(12, 'KALO', 42.55, -92.4, 'WATERLOO        ', 'IA', 'US', '12/17/2018', '12/25/2018', 28, 11, 28.1)
(13, 'KALW', 46.1, -118.28299999999999, 'WALLA WALLA     ', 'WA', 'US', '12/17/2018', '12/25/2018', 35.5, 27.5, 37.6)
(14, 'KAMA', 35.217, -101.71700000000001, 'AMARILLO        ', 'TX', 'US', '12/17/2018', '12/25/2018', 43.5, 23.2, 48.8)
(15, 'KANJ', 46.467, -84.367, 'SAULT STE MARIE', 'MI', 'US', '12/17/2018', '12/25/2018', 21, 12.1, 25.9)
(16, 'KAPC', 38.2, -122.28299999999999, 'NAPA            ', 'CA', 'US', '12/17/2018', '12/25/2018', 46, 35.9, 54.5)
(17, 'KAPN', 45.067, -83.56700000000001, 'ALPENA          ', 'MI', 'US', '12/17/2018', '12/25/2018', 24.5, 15.4, 29.1)
(18, 'KAST', 46.15, -123.883, 'ASTORIA         ', 'OR', 'US', '12/17/2018', '12/25/2018', 43, 36.5, 48.3)
(19, 'KATL', 33.633, -84.45, 'ATLANTA         ', 'GA', 'US', '12/17/2018', '12/25/2018', 49, 34.9, 52.1)
(20, 'KATT', 30.316999999999997, -97.76700000000001, 'AUSTIN/MABRY    ', 'TX', 'US', '12/17/2018', '12/25/2018', 61.5, 41.2, 61.2)
(21, 'KAUS', 30.183000000000003, -97.68299999999999, 'AUSTIN          ', 'TX', 'US', '12/17/2018', '12/25/2018', 63, 36, 62.5)
(22, 'KAVL', 35.433, -82.53299999999999, 'ASHEVILLE       ', 'NC', 'US', '12/17/2018', '12/25/2018', 43, 27.8, 47.7)
(23, 'KAVP', 41.333, -75.717, 'AVOCA/WILKES B. ', 'PA', 'US', '12/17/2018', '12/25/2018', 29, 21, 34.8)
(24, 'KAZO', 42.233000000000004, -85.55, 'KALAMAZOO       ', 'MI', 'US', '12/17/2018', '12/25/2018', 30, 20.1, 32.3)
(25, 'KBAF', 42.167, -72.717, 'WESTFIELD       ', 'MA', 'US', '12/17/2018', '12/25/2018', 27.5, 17.5, 35.5)
(26, 'KBAZ', 29.717, -98.05, 'NEW BRAUNFELS   ', 'TX', 'US', '12/17/2018', '12/25/2018', 64, 39.5, 62.3)
(27, 'KBDL', 41.933, -72.683, 'WINDSOR LOCKS   ', 'CT', 'US', '12/17/2018', '12/25/2018', 28, 20.3, 36.7)
(28, 'KBDR', 41.167, -73.133, 'BRIDGEPORT      ', 'CT', 'US', '12/17/2018', '12/25/2018', 33, 25.5, 39.5)
(29, 'KBFF', 41.867, -103.583, 'SCOTTSBLUFF     ', 'NE', 'US', '12/17/2018', '12/25/2018', 30.5, 11.8, 38.9)
(30, 'KBFL', 35.433, -119.05, 'BAKERSFIELD     ', 'CA', 'US', '12/17/2018', '12/25/2018', 47, 38.6, 55.1)
(31, 'KBGM', 42.217, -75.983, 'BINGHAMTON      ', 'NY', 'US', '12/17/2018', '12/25/2018', 24.5, 18.4, 30.6)
(32, 'KBHM', 33.567, -86.75, 'BIRMINGHAM      ', 'AL', 'US', '12/17/2018', '12/25/2018', 51, 34.9, 54)
(33, 'KBIL', 45.8, -108.55, 'BILLINGS', 'MT', 'US', '12/17/2018', '12/25/2018', 28, 16.7, 34.6)
(34, 'KBIS', 46.766999999999996, -100.75, 'BISMARCK        ', 'ND', 'US', '12/17/2018', '12/25/2018', 23, 3.5, 23.9)
(35, 'KBKL', 41.533, -81.667, 'CLEVELAND       ', 'OH', 'US', '12/17/2018', '12/25/2018', 33, 26.2, 36.5)
(36, 'KBKW', 37.8, -81.117, 'BECKLEY         ', 'WV', 'US', '12/17/2018', '12/25/2018', 36.5, 24.1, 40.2)
(37, 'KBNA', 36.117, -86.68299999999999, 'NASHVILLE       ', 'TN', 'US', '12/17/2018', '12/25/2018', 46.5, 29.7, 47.4)
(38, 'KBNO', 43.6, -118.95, 'BURNS           ', 'OR', 'US', '12/17/2018', '12/25/2018', 20, 13, 33.3)
(39, 'KBOI', 43.567, -116.23299999999999, 'BOISE           ', 'ID', 'US', '12/17/2018', '12/25/2018', 30, 22.9, 36.3)
(40, 'KBOS', 42.367, -71.017, 'BOSTON          ', 'MA', 'US', '12/17/2018', '12/25/2018', 31, 25.2, 38.4)
(41, 'KBPT', 29.95, -94.03299999999999, 'BEAUMONT/PORT AR', 'TX', 'US', '12/17/2018', '12/25/2018', 65, 43.5, 62.2)
(42, 'KBRO', 25.916999999999998, -97.417, 'BROWNSVILLE     ', 'TX', 'US', '12/17/2018', '12/25/2018', 71.5, 51.4, 70.4)
(43, 'KBTR', 30.533, -91.15, 'BATON ROUGE     ', 'LA', 'US', '12/17/2018', '12/25/2018', 60.5, 41.6, 62.7)
(44, 'KBTV', 44.467, -73.15, 'BURLINGTON      ', 'VT', 'US', '12/17/2018', '12/25/2018', 20, 14.5, 30)
(45, 'KBUF', 42.933, -78.733, 'BUFFALO/CHEEKTOW', 'NY', 'US', '12/17/2018', '12/25/2018', 27, 21.5, 33.5)
(46, 'KBUR', 34.2, -118.367, 'BURBANK         ', 'CA', 'US', '12/17/2018', '12/25/2018', 50.5, 41, 66.7)
(47, 'KBWI', 39.167, -76.683, 'BALTO/WASH INTL ', 'MD', 'US', '12/17/2018', '12/25/2018', 35.5, 26, 42.9)
(48, 'KCAE', 33.933, -81.117, 'COLUMBIA        ', 'SC', 'US', '12/17/2018', '12/25/2018', 48, 33.9, 56.2)
(49, 'KCAK', 40.917, -81.45, 'AKRON           ', 'OH', 'US', '12/17/2018', '12/25/2018', 32, 21.3, 34.4)
(50, 'KCAR', 46.867, -68.017, 'CARIBOU         ', 'ME', 'US', '12/17/2018', '12/25/2018', 10, 5.8, 23.2)
(51, 'KCHA', 35.033, -85.2, 'CHATTANOOGA     ', 'TN', 'US', '12/17/2018', '12/25/2018', 46, 31.7, 50.2)
(52, 'KCHO', 38.133, -78.45, 'CHARLOTTESVILLE ', 'VA', 'US', '12/17/2018', '12/25/2018', 39, 26.9, 44.7)
(53, 'KCHS', 32.9, -80.033, 'CHARLESTON      ', 'SC', 'US', '12/17/2018', '12/25/2018', 51, 38.3, 59.6)
(54, 'KCKB', 39.3, -80.217, 'CLARKSBURG      ', 'WV', 'US', '12/17/2018', '12/25/2018', 36.5, 23.6, 41)
(55, 'KCLE', 41.417, -81.85, 'CLEVELAND       ', 'OH', 'US', '12/17/2018', '12/25/2018', 32.5, 23.6, 35.7)
(56, 'KCLL', 30.583000000000002, -96.367, 'COLLEGE STATION ', 'TX', 'US', '12/17/2018', '12/25/2018', 63, 41.1, 60.8)
(57, 'KCLT', 35.217, -80.95, 'CHARLOTTE       ', 'NC', 'US', '12/17/2018', '12/25/2018', 44, 30.4, 50.9)
(58, 'KCMH', 40, -82.883, 'COLUMBUS        ', 'OH', 'US', '12/17/2018', '12/25/2018', 34.5, 24.5, 37.6)
(59, 'KCNK', 39.55, -97.65, 'CONCORDIA       ', 'KS', 'US', '12/17/2018', '12/25/2018', 37.5, 19.1, 37.9)
(60, 'KCON', 43.2, -71.5, 'CONCORD         ', 'NH', 'US', '12/17/2018', '12/25/2018', 24, 13.7, 33.3)
(61, 'KCOS', 38.817, -104.71700000000001, 'COLORADO SPRINGS', 'CO', 'US', '12/17/2018', '12/25/2018', 35.5, 16.9, 41.8)
(62, 'KCOU', 38.817, -92.21700000000001, 'COLUMBIA        ', 'MO', 'US', '12/17/2018', '12/25/2018', 39, 21.7, 38.9)
(63, 'KCPR', 42.9, -106.46700000000001, 'CASPER          ', 'WY', 'US', '12/17/2018', '12/25/2018', 27.5, 13, 33.9)
(64, 'KCQT', 34.016999999999996, -118.28299999999999, 'LOS ANGELES     ', 'CA', 'US', '12/17/2018', '12/25/2018', 54.5, 47.2, 67.4)
(65, 'KCRP', 27.767, -97.5, 'CORPUS CHRISTI  ', 'TX', 'US', '12/17/2018', '12/25/2018', 69.5, 47.3, 67)
(66, 'KCRW', 38.383, -81.583, 'CHARLESTON      ', 'WV', 'US', '12/17/2018', '12/25/2018', 39, 27.3, 43.3)
(67, 'KCSG', 32.516999999999996, -84.95, 'COLUMBUS        ', 'GA', 'US', '12/17/2018', '12/25/2018', 52.5, 37.4, 57.4)
(68, 'KCVG', 39.05, -84.667, 'COVINGTON       ', 'KY', 'US', '12/17/2018', '12/25/2018', 36.5, 24.5, 39.3)
(69, 'KCXY', 40.217, -76.85, 'HARRISBURG      ', 'PA', 'US', '12/17/2018', '12/25/2018', 34.5, 24.5, 39.2)
(70, 'KCYS', 41.15, -104.81700000000001, 'CHEYENNE        ', 'WY', 'US', '12/17/2018', '12/25/2018', 31, 17.2, 38.3)
(71, 'KDAB', 29.183000000000003, -81.067, 'DAYTONA BEACH   ', 'FL', 'US', '12/17/2018', '12/25/2018', 65, 48.6, 68.9)
(72, 'KDAL', 32.85, -96.85, 'DALLAS/LOVE FLD ', 'TX', 'US', '12/17/2018', '12/25/2018', 58, 37.2, 56.1)
(73, 'KDAY', 39.9, -84.21700000000001, 'DAYTON          ', 'OH', 'US', '12/17/2018', '12/25/2018', 34, 22, 35.6)
(74, 'KDBQ', 42.4, -90.7, 'DUBUQUE         ', 'IA', 'US', '12/17/2018', '12/25/2018', 28, 12.7, 27.5)
(75, 'KDCA', 38.85, -77.033, 'WASHINGTON/NATL ', 'DC', 'US', '12/17/2018', '12/25/2018', 39, 30.3, 44.4)
(76, 'KDDC', 37.766999999999996, -99.96700000000001, 'DODGE CITY      ', 'KS', 'US', '12/17/2018', '12/25/2018', 38.5, 20.2, 43)
(77, 'KDEN', 39.833, -104.65, 'DENVER', 'CO', 'US', '12/17/2018', '12/25/2018', 34.5, 16.9, 42.3)
(78, 'KDFW', 32.9, -97.01700000000001, 'DALLAS/FT WORTH ', 'TX', 'US', '12/17/2018', '12/25/2018', 56, 35.7, 55.6)
(79, 'KDLH', 46.85, -92.2, 'DULUTH          ', 'MN', 'US', '12/17/2018', '12/25/2018', 18.5, 4.1, 19.9)
(80, 'KDOV', 39.133, -75.467, 'Dover AFB', 'DE', 'US', '12/17/2018', '12/25/2018', 35.5, 28.6, 44.6)
(81, 'KDRT', 29.366999999999997, -100.917, 'DEL RIO         ', 'TX', 'US', '12/17/2018', '12/25/2018', 60, 39.8, 62.9)
(82, 'KDSM', 41.533, -93.667, 'DES MOINES      ', 'IA', 'US', '12/17/2018', '12/25/2018', 32, 15.8, 31.6)
(83, 'KDTW', 42.233000000000004, -83.333, 'DETROIT/WAYNE   ', 'MI', 'US', '12/17/2018', '12/25/2018', 32, 21.5, 33.5)
(84, 'KDVN', 41.617, -90.583, 'DAVENPORT/QUAD C', 'IA', 'US', '12/17/2018', '12/25/2018', 30.5, 14.5, 30.5)
(85, 'KEAU', 44.867, -91.46700000000001, 'EAU CLAIRE      ', 'WI', 'US', '12/17/2018', '12/25/2018', 23, 7.8, 24.5)
(86, 'KELP', 31.816999999999997, -106.383, 'EL PASO         ', 'TX', 'US', '12/17/2018', '12/25/2018', 52, 31.6, 56)
(87, 'KELY', 39.3, -114.85, 'ELY             ', 'NV', 'US', '12/17/2018', '12/25/2018', 21.5, 10.3, 38.8)
(88, 'KERI', 42.083, -80.183, 'ERIE            ', 'PA', 'US', '12/17/2018', '12/25/2018', 31.5, 23.8, 35.5)
(89, 'KEUG', 44.133, -123.21700000000001, 'EUGENE          ', 'OR', 'US', '12/17/2018', '12/25/2018', 40, 33.3, 44.9)
(90, 'KEVV', 38.05, -87.51700000000001, 'EVANSVILLE      ', 'IN', 'US', '12/17/2018', '12/25/2018', 40, 25.3, 41.9)
(91, 'KEWR', 40.683, -74.167, 'NEWARK          ', 'NJ', 'US', '12/17/2018', '12/25/2018', 34.5, 27, 40.8)
(92, 'KEYW', 24.55, -81.75, 'KEY WEST        ', 'FL', 'US', '12/17/2018', '12/25/2018', 73.5, 65.4, 74.9)
(93, 'KFAR', 46.933, -96.81700000000001, 'FARGO           ', 'ND', 'US', '12/17/2018', '12/25/2018', 19.5, 3, 19.6)
(94, 'KFAT', 36.783, -119.71700000000001, 'FRESNO          ', 'CA', 'US', '12/17/2018', '12/25/2018', 41.5, 37.6, 53.3)
(95, 'KFLG', 35.133, -111.667, 'FLAGSTAFF       ', 'AZ', 'US', '12/17/2018', '12/25/2018', 28, 16.3, 41.7)
(96, 'KFMY', 26.583000000000002, -81.867, 'FORT MYERS      ', 'FL', 'US', '12/17/2018', '12/25/2018', 67.5, 54.8, 75.3)
(97, 'KFNT', 42.967, -83.75, 'FLINT           ', 'MI', 'US', '12/17/2018', '12/25/2018', 27, 18.1, 31.5)
(98, 'KFSD', 43.583, -96.75, 'SIOUX FALLS     ', 'SD', 'US', '12/17/2018', '12/25/2018', 29, 7.6, 26.4)
(99, 'KFSM', 35.333, -94.367, 'FORT SMITH      ', 'AR', 'US', '12/17/2018', '12/25/2018', 50.5, 29.6, 49.7)
(100, 'KFTW', 32.833, -97.367, 'FORT WORTH      ', 'TX', 'US', '12/17/2018', '12/25/2018', 55.5, 34.9, 55.4)
(101, 'KFTY', 33.783, -84.51700000000001, 'ATLANTA/FULTON  ', 'GA', 'US', '12/17/2018', '12/25/2018', 48.5, 33.8, 52.6)
(102, 'KFWA', 40.983000000000004, -85.18299999999999, 'FORT WAYNE      ', 'IN', 'US', '12/17/2018', '12/25/2018', 33, 19.5, 33.6)
(103, 'KFYV', 36.016999999999996, -94.167, 'FAYETTEVILLE    ', 'AR', 'US', '12/17/2018', '12/25/2018', 45.5, 25.4, 46.3)
(104, 'KGAG', 36.3, -99.76700000000001, 'GAGE            ', 'OK', 'US', '12/17/2018', '12/25/2018', 41, 20.2, 47.5)
(105, 'KGEG', 47.617, -117.53299999999999, 'SPOKANE/METRO   ', 'WA', 'US', '12/17/2018', '12/25/2018', 29, 21.6, 31.5)
(106, 'KGFK', 47.95, -97.18299999999999, 'GRAND FORKS     ', 'ND', 'US', '12/17/2018', '12/25/2018', 13.5, -0.4, 17.6)
(107, 'KGGW', 48.217, -106.617, 'GLASGOW         ', 'MT', 'US', '12/17/2018', '12/25/2018', 19, 4.3, 23.6)
(108, 'KGJT', 39.117, -108.51700000000001, 'GRAND JUNCTION  ', 'CO', 'US', '12/17/2018', '12/25/2018', 32, 17, 36.9)
(109, 'KGLD', 39.367, -101.7, 'GOODLAND        ', 'KS', 'US', '12/17/2018', '12/25/2018', 34, 16.6, 41.9)
(110, 'KGLS', 29.267, -94.867, 'GALVESTON       ', 'TX', 'US', '12/17/2018', '12/25/2018', 63, 49.2, 62.5)
(111, 'KGPI', 48.317, -114.25, 'KALISPELL       ', 'MT', 'US', '12/17/2018', '12/25/2018', 22.5, 14.2, 28.6)
(112, 'KGRB', 44.483000000000004, -88.133, 'ASHWAUBENON     ', 'WI', 'US', '12/17/2018', '12/25/2018', 27.5, 11.5, 25.8)
(113, 'KGRI', 40.967, -98.31700000000001, 'GRAND ISLAND    ', 'NE', 'US', '12/17/2018', '12/25/2018', 37, 14.9, 35.3)
(114, 'KGRR', 42.883, -85.51700000000001, 'GRAND RAPIDS    ', 'MI', 'US', '12/17/2018', '12/25/2018', 29.5, 20.9, 32.4)
(115, 'KGSO', 36.1, -79.95, 'GREENSBORO      ', 'NC', 'US', '12/17/2018', '12/25/2018', 41, 30.3, 48.6)
(116, 'KGSP', 34.9, -82.21700000000001, 'GREER/SPARTANSBG', 'SC', 'US', '12/17/2018', '12/25/2018', 44.5, 32.6, 52.2)
(117, 'KGTF', 47.467, -111.383, 'GREAT FALLS     ', 'MT', 'US', '12/17/2018', '12/25/2018', 23, 13.6, 34.1)
(118, 'KGWO', 33.5, -90.083, 'GREENWOOD       ', 'MS', 'US', '12/17/2018', '12/25/2018', 53.5, 34.2, 54.1)
(119, 'KHFD', 41.733000000000004, -72.65, 'HARTFORD/BRAINAR', 'CT', 'US', '12/17/2018', '12/25/2018', 30, 21, 37.7)
(120, 'KHLN', 46.6, -111.96700000000001, 'HELENA          ', 'MT', 'US', '12/17/2018', '12/25/2018', 23, 10.4, 30.6)
(121, 'KHON', 44.383, -98.23299999999999, 'HURON           ', 'SD', 'US', '12/17/2018', '12/25/2018', 26.5, 7.3, 26.9)
(122, 'KHOU', 29.633000000000003, -95.28299999999999, 'HOUSTON/HOBBY   ', 'TX', 'US', '12/17/2018', '12/25/2018', 65.5, 45.5, 63.1)
(123, 'KHSE', 35.233000000000004, -75.617, 'HATTERAS/MITCHEL', 'NC', 'US', '12/17/2018', '12/25/2018', 51, 40.4, 53.8)
(124, 'KHSP', 37.95, -79.817, 'HOT SPRINGS/INGA', 'VA', 'US', '12/17/2018', '12/25/2018', 28, 21.4, 40.1)
(125, 'KHSV', 34.65, -86.78299999999999, 'HUNTSVILLE      ', 'AL', 'US', '12/17/2018', '12/25/2018', 49.5, 32.8, 51.6)
(126, 'KHTL', 44.35, -84.667, 'HOUGHTON LAKE   ', 'MI', 'US', '12/17/2018', '12/25/2018', 23.5, 14.2, 28.1)
(127, 'KHTS', 38.367, -82.55, 'HUNTINGTON      ', 'WV', 'US', '12/17/2018', '12/25/2018', 38.5, 26.7, 43.2)
(128, 'KHVN', 41.266999999999996, -72.867, 'NEW HAVEN/TWEED ', 'CT', 'US', '12/17/2018', '12/25/2018', 31, 25.5, 40.1)
(129, 'KHVR', 48.55, -109.76700000000001, 'HAVRE           ', 'MT', 'US', '12/17/2018', '12/25/2018', 19.5, 6, 28.5)
(130, 'KIAD', 38.933, -77.45, 'WASH DC/DULLES  ', 'VA', 'US', '12/17/2018', '12/25/2018', 35, 25.1, 43.5)
(131, 'KIAH', 30, -95.367, 'HOUSTON/INTNL   ', 'TX', 'US', '12/17/2018', '12/25/2018', 65, 43.4, 62.8)
(132, 'KICT', 37.65, -97.43299999999999, 'WICHITA         ', 'KS', 'US', '12/17/2018', '12/25/2018', 42.5, 22.5, 41.6)
(133, 'KILG', 39.667, -75.6, 'WILMINGTON      ', 'DE', 'US', '12/17/2018', '12/25/2018', 34.5, 26.4, 42)
(134, 'KILM', 34.266999999999996, -77.9, 'WILMINGTON      ', 'NC', 'US', '12/17/2018', '12/25/2018', 46.5, 36.1, 57.1)
(135, 'KIND', 39.717, -86.3, 'INDIANAPOLIS    ', 'IN', 'US', '12/17/2018', '12/25/2018', 35, 22.1, 36.4)
(136, 'KINK', 31.783, -103.2, 'WINK            ', 'TX', 'US', '12/17/2018', '12/25/2018', 52, 27.9, 59.4)
(137, 'KINL', 48.567, -93.4, 'INTERNTNL FALLS ', 'MN', 'US', '12/17/2018', '12/25/2018', 11.5, -3.5, 16.2)
(138, 'KINT', 36.133, -80.217, 'WINSTON SALEM   ', 'NC', 'US', '12/17/2018', '12/25/2018', 41.5, 30.9, 48.9)
(139, 'KINW', 35.033, -110.71700000000001, 'WINSLOW         ', 'AZ', 'US', '12/17/2018', '12/25/2018', 39.5, 19.8, 47.1)
(140, 'KIPT', 41.25, -76.917, 'WILLIAMSPORT    ', 'PA', 'US', '12/17/2018', '12/25/2018', 31.5, 21.6, 35.6)
(141, 'KISN', 48.167, -103.633, 'WILLISTON       ', 'ND', 'US', '12/17/2018', '12/25/2018', 20, 0.7, 22.2)
(142, 'KJAN', 32.317, -90.083, 'JACKSON         ', 'MS', 'US', '12/17/2018', '12/25/2018', 55.5, 36.1, 56.4)
(143, 'KJAX', 30.5, -81.683, 'JACKSONVILLE    ', 'FL', 'US', '12/17/2018', '12/25/2018', 59, 42.2, 65)
(144, 'KJCT', 30.511, -99.766, 'Junction', 'TX', 'US', '12/17/2018', '12/25/2018', 58, 31.2, 60.5)
(145, 'KLAL', 27.989, -82.01899999999999, 'Lakeland Reg AP', 'FL', 'US', '12/17/2018', '12/25/2018', 56, 50.9, 73.4)
(146, 'KLAN', 42.783, -84.583, 'LANSING         ', 'MI', 'US', '12/17/2018', '12/25/2018', 28.5, 19.6, 31.8)
(147, 'KLAS', 36.083, -115.15, 'LAS VEGAS       ', 'NV', 'US', '12/17/2018', '12/25/2018', 46.5, 38.1, 55.9)
(148, 'KLAX', 33.933, -118.383, 'LOS ANGELES     ', 'CA', 'US', '12/17/2018', '12/25/2018', 55.5, 48.3, 64.2)
(149, 'KLBB', 33.667, -101.81700000000001, 'LUBBOCK         ', 'TX', 'US', '12/17/2018', '12/25/2018', 46.5, 26, 52.9)
(150, 'KLBF', 41.117, -100.667, 'NORTH PLATTE    ', 'NE', 'US', '12/17/2018', '12/25/2018', 33, 10.5, 38)
(151, 'KLCH', 30.133000000000003, -93.21700000000001, 'LAKE CHARLES    ', 'LA', 'US', '12/17/2018', '12/25/2018', 63.5, 42.8, 62)
(152, 'KLEX', 38.033, -84.6, 'LEXINGTON       ', 'KY', 'US', '12/17/2018', '12/25/2018', 40.5, 26.1, 41.7)
(153, 'KLFK', 31.233, -94.75, 'LUFKIN          ', 'TX', 'US', '12/17/2018', '12/25/2018', 60.5, 38.1, 59.5)
(154, 'KLFT', 30.2, -92, 'LAFAYETTE       ', 'LA', 'US', '12/17/2018', '12/25/2018', 63.5, 43.3, 62.6)
(155, 'KLGA', 40.783, -73.883, 'LA GUARDIA', 'NY', 'US', '12/17/2018', '12/25/2018', 35, 29.3, 41.6)
(156, 'KLGB', 33.817, -118.15, 'LONG BEACH      ', 'CA', 'US', '12/17/2018', '12/25/2018', 56, 45.4, 66.5)
(157, 'KLIT', 34.733000000000004, -92.23299999999999, 'LITTLE ROCK     ', 'AR', 'US', '12/17/2018', '12/25/2018', 49, 32.2, 50.4)
(158, 'KLND', 42.817, -108.73299999999999, 'LANDER          ', 'WY', 'US', '12/17/2018', '12/25/2018', 20, 8.9, 31.5)
(159, 'KLNK', 40.85, -96.76700000000001, 'LINCOLN         ', 'NE', 'US', '12/17/2018', '12/25/2018', 35.5, 14.7, 35.3)
(160, 'KLNS', 40.117, -76.3, 'LANCASTER       ', 'PA', 'US', '12/17/2018', '12/25/2018', 34.5, 23.3, 39.5)
(161, 'KLRD', 27.533, -99.46700000000001, 'Larado INTL AP', 'TX', 'US', '12/17/2018', '12/25/2018', 70, 45.6, 66.3)
(162, 'KLSE', 43.883, -91.25, 'LA CROSSE       ', 'WI', 'US', '12/17/2018', '12/25/2018', 29.5, 11.3, 26.5)
(163, 'KLUK', 39.1, -84.417, 'CINCINNAT/LUNKEN', 'OH', 'US', '12/17/2018', '12/25/2018', 36, 24, 40.8)
(164, 'KLWS', 46.367, -117.01700000000001, 'LEWISTON        ', 'ID', 'US', '12/17/2018', '12/25/2018', 34, 27.3, 38.7)
(165, 'KLYH', 37.317, -79.2, 'LYNCHBURG       ', 'VA', 'US', '12/17/2018', '12/25/2018', 37.5, 25.6, 45.8)
(166, 'KMAF', 31.95, -102.2, 'MIDLAND         ', 'TX', 'US', '12/17/2018', '12/25/2018', 53, 29.9, 56.8)
(167, 'KMCI', 39.3, -94.73299999999999, 'KANSAS CITY', 'MO', 'US', '12/17/2018', '12/25/2018', 38, 20.6, 38.2)
(168, 'KMCN', 32.683, -83.65, 'MACON           ', 'GA', 'US', '12/17/2018', '12/25/2018', 50.5, 35.1, 57.6)
(169, 'KMCO', 28.416999999999998, -81.333, 'ORLANDO         ', 'FL', 'US', '12/17/2018', '12/25/2018', 64.5, 50.6, 71.5)
(170, 'KMDT', 40.2, -76.767, 'MIDDLETOWN      ', 'PA', 'US', '12/17/2018', '12/25/2018', 33.5, 24.8, 38.8)
(171, 'KMDW', 41.783, -87.75, 'CHICAGO         ', 'IL', 'US', '12/17/2018', '12/25/2018', 33, 20.3, 32.9)
(172, 'KMEI', 32.333, -88.75, 'MERIDIAN/KEY FLD', 'MS', 'US', '12/17/2018', '12/25/2018', 56, 34.3, 56.9)
(173, 'KMEM', 35.067, -89.98299999999999, 'MEMPHIS         ', 'TN', 'US', '12/17/2018', '12/25/2018', 50, 33.5, 50.2)
(174, 'KMFE', 26.183000000000003, -98.25, 'MCALLEN         ', 'TX', 'US', '12/17/2018', '12/25/2018', 74, 50.6, 70.5)
(175, 'KMFR', 42.383, -122.867, 'MEDFORD         ', 'OR', 'US', '12/17/2018', '12/25/2018', 36.5, 32.1, 45.4)
(176, 'KMGM', 32.3, -86.4, 'MONTGOMERY      ', 'AL', 'US', '12/17/2018', '12/25/2018', 52.5, 36.1, 57.6)
(177, 'KMHT', 42.933, -71.433, 'MANCHESTER      ', 'NH', 'US', '12/17/2018', '12/25/2018', 27, 19.2, 35.4)
(178, 'KMIA', 25.8, -80.283, 'MIAMI           ', 'FL', 'US', '12/17/2018', '12/25/2018', 71.5, 61.3, 77)
(179, 'KMKE', 42.95, -87.9, 'MILWAUKEE       ', 'WI', 'US', '12/17/2018', '12/25/2018', 30.5, 17.6, 30.3)
(180, 'KMKG', 43.167, -86.23299999999999, 'MUSKEGON        ', 'MI', 'US', '12/17/2018', '12/25/2018', 31, 23, 32.9)

In [88]:
type(day_df["fcst_mn"][1])

numpy.int64

In [ ]:
# from sqlalchemy import create_engine
# import pymysql
# pymysql.install_as_MySQLdb()

In [ ]:
# engine = create_engine("mysql://root:@localhost/Project2")

In [ ]:
# conn = engine.connect()

In [ ]:
# new_df.to_sql(name='forecast', con=engine, if_exists='append', index=False)

In [ ]:
# data = pd.read_sql("SELECT * FROM forecast", conn)

In [ ]:
# data.head()

In [ ]:
# engine.table_names()

In [ ]:
from sqlalchemy import create_engine

# Imports the methods needed to abstract classes into tables
from sqlalchemy.ext.declarative import declarative_base

# Allow us to declare column types
from sqlalchemy import Column, Integer, String, Float 

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()

In [ ]:
Base = declarative_base()

class Forecast(Base):
    __tablename__ = 'forecast'
    station_id = Column(String, primary_key=True)